### ISSUE TITLE
Can I use this now to create a vAtom?

### ISSUE THREAD

**Issue by jeremy82many** [BLOCKvIO/documentation#1]

**Comment by gthmac** [comment]
BLOCKv has been working heavily towards reaching its Q1 milestone, which will include the launch of the first public beta version of the platform, which will be the time when external developers can make use of the platform using a yet to be communicated onboarding process as well as the needed development tools and documentation.
We will be sending out regular updates on our communication means (medium et al) with regards to this important milestone. The first update will follow in the course of this week (week 7, 2018).
Thanks much for your interest, we are looking forward to you hopefully using the platform.
