### ISSUE TITLE
How i to create blockchain vuetual id

### ISSUE THREAD

**Issue by zihad944** [BLOCKvIO/documentation#2]
I want to create

**Comment by exul** [comment]
If you want to create a vAtom, you'll need a publisher account: https://developer.blockv.io/request-access

Once you have that, you can create vAtoms with or without blockchain integration:
- With blockchain integration: https://developer.blockv.io/docs/tutorial/ethereum-enabled-vatom
- Without blockchain integration: https://developer.blockv.io/docs/tutorial/step-by-step-publishing-a-vatom

Feel free to re-open the issue if that didn't answer your question.
